services:
  - type: web
    name: project-hv
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-render-app.onrender.com,localhost,127.0.0.1"
      - key: AZURE_ACCOUNT_NAME
        sync: false
      - key: AZURE_ACCOUNT_KEY
        sync: false
      - key: AZURE_CONTAINER
        value: "media"